Repository VictoryFairy/VictoryFairy-frontEnd, pull requests merged in 2024-08, with the labels that each got.

#13 [Design] 디자인 시스템 추가
  .eslintrc.cjs
  package-lock.json
  package.json
  src/style/global.ts
  src/style/typography.ts
Labels: 🎨Design

#17 [Chore] 폰트 추가 글로벌 스타일 적용
  index.html
  src/assets/Icons/arrow-down.svg
  src/assets/Icons/arrow-left.svg
  src/assets/Icons/arrow-right.svg
  src/assets/Icons/arrow-up.svg
  src/assets/Icons/arrow2-left.svg
  src/assets/Icons/arrow2-right.svg
  src/assets/Icons/camera.svg
  src/assets/Icons/cancel.svg
  src/assets/Icons/current_location.svg
  src/assets/Icons/delete.svg
  src/assets/Icons/download.svg
  src/assets/Icons/edit.svg
  src/assets/Icons/filter.svg
  src/assets/Icons/heart.svg
  src/assets/Icons/heart_fill.svg
  src/assets/Icons/hide.svg
  src/assets/Icons/home.svg
  src/assets/Icons/info.svg
  src/assets/Icons/location.svg
  src/assets/Icons/menu.svg
  src/assets/Icons/minus.svg
  src/assets/Icons/mypage.svg
  src/assets/Icons/naver.svg
  src/assets/Icons/placeholder12.svg
  src/assets/Icons/placeholder14.svg
  src/assets/Icons/placeholder16.svg
  src/assets/Icons/placeholder20.svg
  src/assets/Icons/placeholder24.svg
  src/assets/Icons/plus.svg
  src/assets/Icons/ranking.svg
  src/assets/Icons/search.svg
  src/assets/Icons/share.svg
  src/assets/Icons/show.svg
  src/assets/Icons/switch.svg
  src/main.tsx
Labels: ✏️Chore

#28 Feat/#19 : Footer nav 구현
  package-lock.json
  package.json
  src/assets/Icons/home.svg
  src/assets/Icons/info.svg
  src/assets/Icons/mypage.svg
  src/assets/Icons/ranking.svg
  src/components/common/Footer.tsx
  src/custom.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ✨Feature

#30 Feature/#29 Header nav 구현
  .eslintrc.cjs
  src/App.tsx
  src/components/common/Header.tsx
  src/components/layout/Layout.tsx
Labels: ✨Feature

#21 Feat/#20: 팝업 모달 구현
  src/components/modal/ModalPortal.tsx
  src/components/modal/Popup.tsx
  src/hooks/usePopup.tsx
Labels: ✨Feature

#22 💄 [Feature] 공통 인풋 컴포넌트 (zod,리액트훅폼)
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/common/InputField.tsx
Labels: ✨Feature

#27 Feat/#27 홈페이지 제작
  src/App.tsx
  src/components/common/Button.tsx
  src/pages/Home.tsx
Labels: ✨Feature

#33 Feat/#31 회원가입 페이지 구현
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/InputField.tsx
  src/components/common/OTPInput.tsx
  src/components/common/TitleSection.tsx
  src/components/signup/EmailValid.tsx
  src/components/signup/EmailVerificationTimer.tsx
  src/components/signup/PasswordValid.tsx
  src/components/signup/Profile.tsx
  src/components/signup/TeamSelect.tsx
  src/components/signup/VerificationCode.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/style/global.ts
  src/types/User.ts
Labels: ✨Feature

#35 Feat/#34 로그인 페이지 구현
  src/App.tsx
  src/components/signup/EmailValid.tsx
  src/components/signup/PasswordValid.tsx
  src/components/signup/VerificationCode.tsx
  src/pages/Signup.tsx
Labels: ✨Feature

#37 Feat/#36 비밀번호 찾기 페이지 구현
  src/App.tsx
  src/components/common/InputField.tsx
  src/components/passwordReset/Confirmpassword.tsx
  src/components/passwordReset/EmailValid.tsx
  src/components/passwordReset/PassWordReset.tsx
  src/components/passwordReset/VerificationCode.tsx
  src/pages/Login.tsx
  src/pages/PasswordReset.tsx
Labels: ✨Feature

#43 Feature/#42 padding및 css설정
  package-lock.json
  package.json
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/layout/Layout.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/PasswordReset.tsx
  src/pages/Signup.tsx
Labels: ✨Feature

#48 Feature/#44 마이페이지 css구현
  src/App.tsx
  src/components/common/Footer.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileButtons.tsx
  src/pages/MyPage.tsx
Labels: ✨Feature

#40 Chore/#39 모바일 환경에서 접속 가능한 스크립트 추가
  package.json
Labels: ✏️Chore, 🛠️Config

#49 Fix/#41 모바일에서 input 확대 되는 버그
  index.html
Labels: 🐛Fix

#52 Chore/#51 svg import 에러
  src/vite-env.d.ts
Labels: ✏️Chore, 🐛Fix

#53 Feat/#50 팀 별 테마 ThemeContextProvider 추가
  src/App.tsx
  src/components/common/Footer.tsx
  src/context/ThemeContext.tsx
  src/main.tsx
  src/style/theme.ts
Labels: ✨Feature, 🎨Design

#57 Feat/#46 유저 인증과 관련된 api, axios 인스턴스 생성, 토큰관리
  .env.development
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/auth/auth.api.ts
  src/api/authAxios.ts
  src/api/axios.ts
  src/components/common/OTPInput.tsx
  src/components/layout/Layout.tsx
  src/components/passwordReset/Confirmpassword.tsx
  src/components/passwordReset/EmailValid.tsx
  src/components/passwordReset/VerificationCode.tsx
  src/components/signup/EmailValid.tsx
  src/components/signup/Profile.tsx
  src/components/signup/TeamSelect.tsx
  src/components/signup/VerificationCode.tsx
  src/pages/Login.tsx
  src/pages/PasswordReset.tsx
  src/pages/Signup.tsx
  src/store/authStore.ts
  src/types/User.ts
Labels: ✨Feature

#61 Feat/#57 메인페이지 UI
  package-lock.json
  package.json
  src/App.tsx
  src/assets/Icons/lose.svg
  src/assets/Icons/no-game.svg
  src/assets/Icons/tie.svg
  src/assets/Icons/win.svg
  src/components/common/Calendar.tsx
  src/components/common/SelectionBar.tsx
  src/components/common/Tabs.tsx
  src/components/todayMatch/TodayMatchItem.tsx
  src/components/todayMatch/TodayMatchList.tsx
  src/components/watchList/WatchList.tsx
  src/pages/main/Main.tsx
  src/pages/main/Rate.tsx
  src/pages/main/Watch.tsx
  src/style/global.ts
Labels: ✨Feature, 🎨Design

#60 Feature/#59 마이페이지 ui 재구현
  src/assets/Icons/arrow-left.svg
  src/assets/Icons/arrow-right.svg
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileButtons.tsx
  src/pages/MyPage.tsx
Labels: ✨Feature

#62 Feat/#47 지도 페이지 개발(api, 리액트쿼리는 주석처리)
  .env.development
  .eslintrc.cjs
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/api/authAxios.ts
  src/api/info/info.api.ts
  src/components/common/Footer.tsx
  src/components/info/map/LocationButton.tsx
  src/components/info/map/Map.tsx
  src/components/info/map/ParkingInfoPage.tsx
  src/components/info/map/ParkingList.tsx
  src/components/info/map/StadiumList.tsx
  src/components/info/map/ZoomButton.tsx
  src/components/layout/Layout.tsx
  src/pages/Info.tsx
  src/types/Stadium.ts
Labels: ✨Feature, 🎨Design

#67 🔧 글로벌스타일 unset 삭제
  src/components/watchList/WatchList.tsx
  src/style/global.ts
Labels: 🐛Fix, 🎨Design

#76 Feat/#63 테마를 위한 유틸함수 제작
  src/components/info/map/ParkingInfoPage.tsx
  src/components/signup/TeamSelect.tsx
  src/pages/Login.tsx
  src/store/authStore.ts
  src/utils/getStadiumId.ts
  src/utils/getTeamName.ts
Labels: ✨Feature

#81 ✨ TextArea 공통컴포넌트 제작
  src/components/common/TextAreaField.tsx
  src/components/signup/EmailValid.tsx
Labels: ✨Feature

#79 ♻️ 인풋필드 공통컴포넌트 수정
  src/components/common/InputField.tsx
Labels: ✏️Chore

#71 Chore/#65 공통 모달 컴포넌트 수정
  src/components/modal/Popup.tsx
  src/components/mypage/ProfileButtons.tsx
  src/hooks/usePopup.tsx
Labels: ✏️Chore

#73 Feat/#70 Text 공통 컴포넌트 추가
  src/components/common/Text.tsx
Labels: ✨Feature, 🎨Design

#75 Chore/#74 버튼 공통 컴포넌트 수정
  src/components/common/Button.tsx
  src/components/passwordReset/VerificationCode.tsx
  src/components/signup/EmailValid.tsx
  src/components/signup/VerificationCode.tsx
  src/pages/Home.tsx
  src/style/button.ts
Labels: ✏️Chore

#83 Feature/#72 마이페이지 프로필, 응원팀 ui 구현
  src/App.tsx
  src/assets/Icons/camera.svg
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/mypage/ProfileButtons.tsx
  src/components/mypage/ProfileChange.tsx
  src/components/mypage/TeamChange.tsx
Labels: ✨Feature

#86 Feat/#84 오늘의경기 리스트 API 연동
  src/api/game/game.ts
  src/components/todayMatch/TodayMatchItem.tsx
  src/components/todayMatch/TodayMatchList.tsx
Labels: ✨Feature

#87 Feat/#82 지도 페이지 완성
  src/api/info/info.api.ts
  src/components/info/map/Map.tsx
  src/components/info/map/ParkingInfoPage.tsx
  src/components/info/map/ParkingList.tsx
  src/components/info/map/StadiumList.tsx
  src/components/layout/Layout.tsx
  src/types/Stadium.ts
Labels: ✨Feature

#89 Feat/#58 내직관 - 리스트 UI
  src/components/common/Calendar.tsx
  src/components/watchList/GameListItem.tsx
  src/components/watchList/ListTab.tsx
  src/components/watchList/ResultLabel.tsx
  src/components/watchList/WatchList.tsx
  src/types/Game.ts
Labels: ✨Feature, 🎨Design

#91 Feat/#90 svg 공통 컴포넌트 추가
  src/assets/Icons/_index.ts
  src/assets/Icons/arrow-down.svg
  src/assets/Icons/arrow-left.svg
  src/assets/Icons/arrow-up.svg
  src/assets/Icons/arrow2-left.svg
  src/assets/Icons/arrow2-right.svg
  src/assets/Icons/cancel.svg
  src/assets/Icons/current_location.svg
  src/assets/Icons/delete.svg
  src/assets/Icons/download.svg
  src/assets/Icons/edit.svg
  src/assets/Icons/filter.svg
  src/assets/Icons/heart.svg
  src/assets/Icons/heart_fill.svg
  src/assets/Icons/hide.svg
  src/assets/Icons/info.svg
  src/assets/Icons/location.svg
  src/assets/Icons/menu.svg
  src/assets/Icons/minus.svg
  src/assets/Icons/naver.svg
  src/assets/Icons/placeholder12.svg
  src/assets/Icons/placeholder14.svg
  src/assets/Icons/placeholder16.svg
  src/assets/Icons/placeholder20.svg
  src/assets/Icons/placeholder24.svg
  src/assets/Icons/plus.svg
  src/assets/Icons/search.svg
  src/assets/Icons/share.svg
  src/assets/Icons/show.svg
  src/assets/Icons/switch.svg
  src/assets/Icons/win.svg
  src/components/common/Icon.tsx
  src/types/Icons.ts
Labels: ✨Feature, ♻️Refactor

#92 Feature/#85 랭킹 ui구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/ranking/RankingTab.tsx
  src/pages/Ranking.tsx
Labels: ✨Feature

#93 Feat/#88 응원가 페이지 ui 완성
  src/App.tsx
  src/api/authAxios.ts
  src/api/info/info.api.ts
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/info/cheerSong/TeamList.tsx
  src/components/info/map/ParkingInfoPage.tsx
  src/components/layout/Layout.tsx
  src/pages/Info.tsx
  src/pages/SearchCheerSong.tsx
  src/store/authStore.ts
  src/types/Team.ts
Labels: ✨Feature

#103 Chore/#102 공통 Text컴포넌트 수정
  src/App.tsx
  src/components/common/Text.tsx
Labels: ✏️Chore

#100 Feat/#94 유저인증페이지 레이아웃 추가(뒤로가기 기능)
  src/App.tsx
  src/components/passwordReset/Confirmpassword.tsx
  src/components/signup/TeamSelect.tsx
  src/pages/Login.tsx
  src/pages/PasswordReset.tsx
  src/pages/Signup.tsx
  src/store/signupStep.ts
Labels: ✨Feature

#98 Feat/#96 세부페이지 UI
  src/App.tsx
  src/components/common/GameListItem.tsx
  src/components/common/InputField.tsx
  src/components/common/TextAreaField.tsx
  src/components/watchList/ListTab.tsx
  src/components/watchList/ListTab/ListTab.tsx
  src/components/watchList/ListTab/ResultLabel.tsx
  src/components/watchList/WatchList.tsx
  src/pages/Post.tsx
Labels: 🎨Design

#104 Feat/#101 지도페이지 svg추가
  src/components/info/map/LocationButton.tsx
  src/components/info/map/ParkingList.tsx
Labels: ✨Feature

#107 Chore/#105 랭킹페이지 공통컴포넌트들로 변경
  src/components/ranking/RankingTab.tsx
Labels: ✏️Chore, 🎨Design

#109 Chore/#108 마이페이지 공통 컴포넌트로 변경
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileButtons.tsx
  src/components/mypage/ProfileChange.tsx
  src/components/mypage/TeamChange.tsx
  src/pages/MyPage.tsx
Labels: ✏️Chore, 🛠️Config

#113 Feature/#112 마이페이지 회원탈퇴 모달 구현
  package-lock.json
  package.json
  src/components/modal/Popup.tsx
  src/components/mypage/ProfileButtons.tsx
  src/components/ranking/RankPopup.tsx
  src/components/ranking/RankingTab.tsx
  src/hooks/usePopup.tsx
Labels: ✨Feature

#118 Feature/#114 마이페이지 모달 ui 구현
  .eslintrc.cjs
  src/components/ranking/MyRankComp.tsx
  src/components/ranking/RankPopup.tsx
  src/components/ranking/RankTextComp.tsx
  src/components/ranking/RankingTab.tsx
Labels: ✨Feature

#126 [Chore] Footer안쓰는 페이지 조정
  src/App.tsx
  src/components/layout/Layout.tsx
  src/components/mypage/ProfileButtons.tsx
Labels: ✏️Chore

#116 Config/#115 import " ../ " -> @ 로 변경
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/common/Button.tsx
  src/components/common/Calendar.tsx
  src/components/common/Footer.tsx
  src/components/common/GameListItem.tsx
  src/components/common/Icon.tsx
  src/components/common/MonthNav.tsx
  src/components/common/SearchBar.tsx
  src/components/common/SelectionBar.tsx
  src/components/common/Tabs.tsx
  src/components/common/Text.tsx
  src/components/common/TitleSection.tsx
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/info/cheerSong/TeamList.tsx
  src/components/info/map/LocationButton.tsx
  src/components/info/map/Map.tsx
  src/components/info/map/ParkingInfoPage.tsx
  src/components/info/map/ParkingList.tsx
  src/components/info/map/StadiumList.tsx
  src/components/modal/Popup.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileButtons.tsx
  src/components/mypage/ProfileChange.tsx
  src/components/mypage/TeamChange.tsx
  src/components/passwordReset/Confirmpassword.tsx
  src/components/passwordReset/EmailValid.tsx
  src/components/passwordReset/PassWordReset.tsx
  src/components/passwordReset/VerificationCode.tsx
  src/components/signup/EmailValid.tsx
  src/components/signup/EmailVerificationTimer.tsx
  src/components/signup/PasswordValid.tsx
  src/components/signup/Profile.tsx
  src/components/signup/TeamSelect.tsx
  src/components/signup/VerificationCode.tsx
  src/components/todayMatch/TodayMatchItem.tsx
  src/components/todayMatch/TodayMatchList.tsx
  src/components/watchList/GalleryTab/GalleryTab.tsx
  src/components/watchList/WatchList.tsx
  src/pages/main/Main.tsx
  src/pages/main/Rate.tsx
  src/pages/main/Watch.tsx
  tsconfig.app.json
  tsconfig.paths.json
  vite.config.ts
Labels: 🛠️Config

#120 Feat/#99 내 직관 등록하기 구현
  src/App.tsx
  src/api/register/register.ts
  src/components/common/Button.tsx
  src/components/common/Calendar.tsx
  src/components/common/GameListItem.tsx
  src/components/common/Radio.tsx
  src/components/dailyMatch/DailyMatch.tsx
  src/components/dailyMatch/DailyMatchItem.tsx
  src/components/register/CheerTeamSelect.tsx
  src/components/todayMatch/TodayMatchList.tsx
  src/hooks/useGame.tsx
  src/pages/Register/RegisterForm.tsx
  src/pages/Register/SelectMatch.tsx
  src/types/Game.ts
  src/utils/uploadImg.ts
Labels: ✨Feature, 🎨Design

#127 Feat/#106 응원가 페이지 작업
  package-lock.json
  package.json
  src/App.tsx
  src/api/info/cheers.api.ts
  src/assets/images/Group 625793.png
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/info/cheerSong/TeamList.tsx
  src/pages/CheersongDetail.tsx
  src/pages/SearchCheerSong.tsx
  src/types/Player.ts
Labels: ✨Feature

#131 chore/#130 🔧직관등록 폴더명 수정 Register -> register
  src/pages/register/RegisterForm.tsx
  src/pages/register/SelectMatch.tsx
Labels: ✏️Chore

#132 Feat/#128 좋아요, 좋아요취소, my응원가 무한스크롤 추가
  src/App.tsx
  src/api/info/cheers.api.ts
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/info/cheerSong/CheerSongPage.tsx
Labels: ✨Feature

#133 Feature/#119 정보 불러오기, 로그아웃 구현
  .eslintrc.cjs
  src/api/auth/auth.api.ts
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileButtons.tsx
  src/store/userInfo.ts
  src/types/UserInfo.ts
Labels: ✨Feature

#139 Feat/#138 응원 팀 경기 최상단 Default 선택 되도록하기
  src/assets/Icons/_index.ts
  src/assets/Icons/polygon.svg
  src/components/dailyMatch/DailyMatch.tsx
  src/components/dailyMatch/DailyMatchItem.tsx
  src/utils/setCheerTeamFirst.ts
Labels: ✨Feature, ✏️Chore

#140 Feat/#134 최신검색기록 구현
  src/components/info/cheerSong/CheerSongList.tsx
  src/pages/SearchCheerSong.tsx
Labels: ✨Feature

#141 ✨ 인증번호 input 복사붙어넣기 추가
  .eslintrc.cjs
  src/components/common/OTPInput.tsx
Labels: ✨Feature

#148 Chore/#143 네이버 지도 api키 env 추가
  .env.development
  index.html
Labels: ✏️Chore

#150 Chore/#149 Env파일 삭제
  .env.development
  .gitignore
Labels: ✏️Chore

#147 🐛 무한스크롤 리팩토링
  src/components/info/cheerSong/CheerSongPage.tsx
Labels: ♻️Refactor

#145 Chore/#144 직관 등록하기 버튼 테마컬러 적용
  src/App.tsx
  src/pages/main/Main.tsx
Labels: ✏️Chore

#146 Feature/#137 랭킹 api 연결
  src/api/rank/rank.api.ts
  src/components/ranking/MyRankComp.tsx
  src/components/ranking/RankBar.tsx
  src/components/ranking/RankPopup.tsx
  src/components/ranking/RankTextComp.tsx
  src/components/ranking/RankingTab.tsx
  src/types/Rank.ts
Labels: ✨Feature

#158 Refactor/#156 지도 중심점 이탈해결
  src/components/info/map/Map.tsx
  src/components/info/map/ZoomButton.tsx
Labels: ♻️Refactor

#160 Refactor/#159 정보페이지 탭유지
  src/pages/CheersongDetail.tsx
  src/pages/Info.tsx
Labels: ♻️Refactor

#161 Feat/#136 내가 등록한 직관 불러오기 API 연결
  src/App.tsx
  src/api/game/game.ts
  src/api/register/register.ts
  src/components/common/Calendar.tsx
  src/components/common/GameListItem.tsx
  src/components/watchList/GalleryTab/GalleryTab.tsx
  src/components/watchList/ListTab/ListTab.tsx
  src/components/watchList/ListTab/ResultLabel.tsx
  src/components/watchList/WatchList.tsx
  src/pages/Detail.tsx
  src/types/Game.ts
  src/utils/uploadImg.ts
Labels: ✏️Chore

#162 Feature/#152 마이페이지 api구현
  src/App.tsx
  src/api/auth/auth.api.ts
  src/api/mypage/mypage.api.ts
  src/components/modal/Popup.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileButtons.tsx
  src/components/mypage/ProfileChange.tsx
  src/components/mypage/TeamChange.tsx
  src/hooks/usePopup.tsx
  src/store/authStore.ts
  src/store/userInfo.ts
  src/types/UserInfo.ts
Labels: ✨Feature

#164 Refactor/#163 무한스크롤 리팩토링(멘토링)
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/info/map/ParkingInfoPage.tsx
  src/utils/getTeamId.ts
Labels: ♻️Refactor

#166 Chore/#165 스네이크 케이스 => 카멜케이스 수정
  src/api/info/cheers.api.ts
  src/api/info/info.api.ts
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/info/map/StadiumList.tsx
  src/pages/SearchCheerSong.tsx
  src/types/Stadium.ts
Labels: ✏️Chore

#170 Chore/#169 비밀번호 검증 수정
  src/App.tsx
  src/components/common/InputField.tsx
  src/components/signup/PasswordValid.tsx
Labels: ✏️Chore

#172 Chore/#171 프로필 컴포넌트 수정, 좋아요 액티브 추가
  src/App.tsx
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/signup/Profile.tsx
  src/pages/CheersongDetail.tsx
Labels: ✏️Chore

#176 [Chore] 랭킹 페이지 api연결
  src/App.tsx
  src/api/rank/rank.api.ts
  src/components/ranking/MyRankComp.tsx
  src/components/ranking/RankBar.tsx
  src/components/ranking/RankPopup.tsx
  src/components/ranking/RankTextComp.tsx
  src/components/ranking/RankingTab.tsx
  src/types/Rank.ts
Labels: ✏️Chore

#178 Chore#174 세부페이지 api 연결
  src/App.tsx
  src/api/rank/rank.api.ts
  src/api/register/register.ts
  src/components/ranking/MyRankComp.tsx
  src/components/ranking/RankBar.tsx
  src/components/ranking/RankPopup.tsx
  src/components/ranking/RankTextComp.tsx
  src/components/ranking/RankingTab.tsx
  src/components/watchList/WatchList.tsx
  src/pages/Detail.tsx
  src/types/Rank.ts
Labels: ✏️Chore

#183 Refactor/#182 인증api 수정
  src/api/auth/auth.api.ts
  src/components/passwordReset/Confirmpassword.tsx
  src/components/passwordReset/VerificationCode.tsx
  src/components/signup/Profile.tsx
  src/components/signup/TeamSelect.tsx
  src/components/signup/VerificationCode.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
Labels: ♻️Refactor

#180 Chore/#179 직관경기등록, 경기목록 API 에러 추가
  src/api/game/game.ts
  src/api/register/register.ts
  src/pages/register/RegisterForm.tsx
Labels: ✏️Chore

#186 [chore/#185] 직관 등록 수정
  src/components/dailyMatch/DailyMatch.tsx
  src/pages/register/RegisterForm.tsx
  src/pages/register/SelectMatch.tsx
  src/utils/setCheerTeamFirst.ts
Labels: ✏️Chore

#193 Chore/#192 좋아요 최종수정
  src/components/info/cheerSong/CheerSongList.tsx
  src/pages/SearchCheerSong.tsx
Labels: ✏️Chore

#194 Feature/#184 승률 차트 생성
  .eslintrc.cjs
  src/api/home/home.api.ts
  src/components/main/DonutChart.tsx
  src/components/ranking/RankBar.tsx
  src/pages/main/Rate.tsx
  src/types/Record.ts
Labels: ✨Feature

#197 Chore/#196 ♻️ 각종 오류 수정
  src/api/register/register.ts
  src/components/common/Calendar.tsx
  src/components/dailyMatch/DailyMatch.tsx
  src/components/todayMatch/TodayMatchItem.tsx
  src/components/todayMatch/TodayMatchList.tsx
  src/components/watchList/GalleryTab/GalleryTab.tsx
  src/components/watchList/WatchList.tsx
  src/pages/main/Main.tsx
  src/pages/register/RegisterForm.tsx
  src/utils/findCheerTeam.ts
  src/utils/setCheerTeamFirst.ts
Labels: ✏️Chore

#198 Feature/#195 파이차트 추가
  package-lock.json
  package.json
  src/App.tsx
  src/api/home/home.api.ts
  src/components/main/CircleChart.tsx
  src/components/main/DonutChart.tsx
  src/pages/main/DetailRate.tsx
  src/pages/main/Rate.tsx
Labels: ✨Feature

#200 {Chore] 차트 오류 수정
  src/App.tsx
  src/components/main/CircleChart.tsx
  src/components/ranking/RankBar.tsx
Labels: ✏️Chore

#202 [Chore] 바 랭킹 수정
  src/components/ranking/RankBar.tsx
  src/components/ranking/RankPopup.tsx
  src/components/ranking/RankingTab.tsx
Labels: ✏️Chore

#205 [Chore] 차트수정
  src/components/main/CircleChart.tsx
  src/components/ranking/MyRankComp.tsx
  src/components/ranking/RankBar.tsx
  src/components/ranking/RankPopup.tsx
  src/components/ranking/RankTextComp.tsx
  src/components/ranking/RankingTab.tsx
  src/types/Rank.ts
Labels: ✏️Chore

#206 Feature/#203 이미지저장, 카톡공유
  index.html
  package-lock.json
  package.json
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/passwordReset/EmailValid.tsx
  src/components/signup/EmailValid.tsx
  src/pages/main/Rate.tsx
Labels: ✨Feature

#207 [Chore] 바 색상 수정
  src/components/ranking/RankBar.tsx
Labels: ✏️Chore

#209 [Chore] 팝업 드래그 수정
  src/components/ranking/RankPopup.tsx
Labels: ✏️Chore

#217 Chore/#216 멘토링 피드백 반영
  src/components/info/cheerSong/TeamList.tsx
  src/components/info/map/LocationButton.tsx
  src/components/info/map/Map.tsx
  src/components/info/map/ParkingInfoPage.tsx
  src/components/info/map/StadiumList.tsx
Labels: ✏️Chore

#218 Chore/#211 자잘한거 수정하기
  package-lock.json
  package.json
  src/App.tsx
  src/api/register/register.ts
  src/components/common/Calendar.tsx
  src/components/common/MonthNav.tsx
  src/components/watchList/ListTab/ListTab.tsx
  src/components/watchList/WatchList.tsx
  src/hooks/useGame.tsx
  src/hooks/useRegisteredGame.tsx
  src/pages/main/Main.tsx
  src/pages/register/SelectMatch.tsx
Labels: ✏️Chore

#226 ✨ 지도리스트 클릭시 인포윈도우 열기
  src/components/common/ToolTip.tsx
  src/components/info/map/Map.tsx
  src/pages/Info.tsx
Labels: ✏️Chore
