Repository VictoryFairy/VictoryFairy-frontEnd, pull requests merged in 2024-09, with the labels that each got.

#252 [Refactor] 회원탈퇴 모달 구현
  src/components/mypage/ProfileButtons.tsx
  src/components/mypage/WithDrawPopup.tsx
Labels: ♻️Refactor

#253 Refactor/#250 팝업 모달 리팩토링
  src/components/modal/Popup.tsx
  src/components/mypage/ProfileButtons.tsx
  src/components/mypage/ProfileChange.tsx
  src/components/mypage/TeamChange.tsx
  src/components/passwordReset/Confirmpassword.tsx
  src/components/signup/TeamSelect.tsx
  src/hooks/usePopup.tsx
  src/pages/detail/Detail.tsx
  src/pages/register/RegisterForm.tsx
Labels: ♻️Refactor

#257 ♻️ 맵, 무한스크롤, 검색바 리팩토링
  .eslintrc.cjs
  src/App.tsx
  src/components/common/ErrorBoundary.tsx
  src/components/common/SearchBar.tsx
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/info/cheerSong/TeamList.tsx
  src/components/info/map/Map.tsx
  src/components/info/map/ParkingInfoPage.tsx
  src/components/info/map/ParkingList.tsx
  src/components/info/map/StadiumList.tsx
  src/components/info/map/ZoomButton.tsx
  src/components/layout/Layout.tsx
  src/pages/Error.tsx
  src/pages/Info.tsx
  src/pages/NotFound.tsx
  src/pages/SearchCheerSong.tsx
Labels: ♻️Refactor

#259 [Chore] 마이페이지 디자인 수정
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileButtons.tsx
  src/components/mypage/ProfileChange.tsx
  src/components/mypage/TeamChange.tsx
Labels: ✏️Chore, 🎨Design

#262 Chore/#260 랭킹 디자인 변경
  src/App.tsx
  src/components/mypage/ProfileButtons.tsx
  src/components/mypage/TeamChange.tsx
  src/components/ranking/MyRankComp.tsx
  src/components/ranking/RankBar.tsx
  src/components/ranking/RankPopup.tsx
  src/components/ranking/RankTextComp.tsx
  src/components/ranking/RankingTab.tsx
Labels: 🎨Design

#263 Chore/#261 디자인 qa 완료
  src/assets/images/cheersEmpty/Group 625793.png
  src/components/common/InputField.tsx
  src/components/common/SearchBar.tsx
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/info/cheerSong/TeamList.tsx
  src/components/info/map/LocationButton.tsx
  src/components/info/map/ParkingList.tsx
  src/components/info/map/StadiumList.tsx
  src/components/info/map/ZoomButton.tsx
  src/components/passwordReset/EmailValid.tsx
  src/components/passwordReset/PassWordReset.tsx
  src/components/signup/EmailValid.tsx
  src/components/signup/PasswordValid.tsx
  src/pages/Info.tsx
  src/pages/Login.tsx
  src/utils/getFullTeamName.ts
Labels: ✏️Chore

#268 💄 디자인 qa최종 수정
  src/components/info/cheerSong/CheerSongList.tsx
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/info/cheerSong/TeamList.tsx
Labels: ✏️Chore

#270 ♻️ 에러바운더리, 에러 처리 추가
  src/api/auth/auth.api.ts
  src/components/info/cheerSong/CheerSongPage.tsx
  src/components/info/map/ParkingInfoPage.tsx
Labels: ♻️Refactor

#271 [Chore] 글짜 찌그러짐
  src/components/ranking/RankBar.tsx
Labels: 🎨Design

#273 Chore/#266 직관 기록에서 모든 경기 선택 가능하게 수정 및 경기item 수정
  src/components/common/GameListItem.tsx
  src/components/common/ResultLabel.tsx
  src/components/dailyMatch/DailyMatch.tsx
  src/components/dailyMatch/DailyMatchItem.tsx
  src/components/register/CheerTeamSelect.tsx
  src/components/register/RegisterFormFields.tsx
  src/components/watchList/ListTab/ListTab.tsx
  src/components/watchList/ListTab/ResultLabel.tsx
  src/components/watchList/WatchList.tsx
  src/components/watchList/calendarTab/CalendarTab.tsx
  src/pages/detail/Detail.tsx
  src/pages/register/RegisterForm.tsx
  src/pages/register/SelectMatch.tsx
  src/types/Game.ts
Labels: ✏️Chore, ♻️Refactor

#275 Refactor/#274 라우터 분리, 코드 복잡도 개선, 성능 개선
  .eslintrc.cjs
  image.d.ts
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/Icons/_index.ts
  src/components/common/Calendar.tsx
  src/components/common/InputField.tsx
  src/components/mypage/ProfileChange.tsx
  src/components/ranking/RankTextComp.tsx
  src/pages/Error.tsx
  src/router/Router.tsx
  src/style/theme.ts
  src/utils/getFullTeamName.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
Labels: ♻️Refactor

#277 Refactor/#276 이미지 파일 png -> webp 변경
  src/pages/main/Main.tsx
  src/pages/main/Rate.tsx
  src/utils/getFairyImg.ts
Labels: ♻️Refactor

#278 Chore#269 티켓 배경 background-img로 추가 다운로드 시 티켓모양으로 다운
  public/ticket.webp
  src/components/todayMatch/TodayMatchList.tsx
  src/pages/main/Main.tsx
  src/pages/main/Rate.tsx
  src/pages/main/Watch.tsx
Labels: ✏️Chore, 🎨Design
